# Generated by Django 3.2.14 on 2022-08-20 05:31

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_favorite_and_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Time must be equal or more then 1')], verbose_name='cooking time in minutes'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Amount must be equal or more then 1')], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FF4136', 'red'), ('#2ECC40', 'green'), ('#0074D9', 'blue'), ('#FFDC00', 'yellow')], verbose_name='tag color'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='tag slug'),
        ),
    ]
