# Generated by Django 3.2.14 on 2022-08-22 15:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, null=True, populate_from='name', unique=True, verbose_name='tag slug'),
        ),
    ]
